name: Generate Manifest on Release


on:
  release:
    types: [published, edited]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REPO: ${{ github.repository }}
        run: |
          python scripts/generate_manifest.py

      - name: Upload Manifest to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/upload_manifest.py
